### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by DevanB** [webnuts/ember-cli-share-this#1]
Is this project still maintained?

If so -have you considered adding this module to NPM? I have had to fork and make available on NPM to go around the need for `git+ssh`.

If not - would you consider transferring the repository to be maintained by someone else (particularly me)?

Thanks!

**Comment by martinthogersen** [comment]
Hey DevanB.

Thank you for your suggestion. I'll make it available ASAP as a NPM module.

**Comment by DevanB** [comment]
Thanks for the quick response @martinthogersen!

I've sent an enquiry to NPM to unpublish the package I published, so you can use the package name. I'll let you know when that is done. Don't want to step on your toes since this was originally your work! 

Thanks for being so prompt!

**Comment by martinthogersen** [comment]
Thanks. Let me know when it's done. I'll publish it within two days after the name is available 👍

**Comment by DevanB** [comment]
@martinthogersen: I've heard back from npm. They said they can transfer the ownership to your npm username, if you can supply me with that username.

**Comment by martinthogersen** [comment]
@DevanB You can find another published ember-cli package from me here: https://www.npmjs.com/package/ember-cli-honeybadger

**Comment by DevanB** [comment]
npm has responded and said you are now the proud owner of the ember-cli-share-this module! They also noted that you will not be able to release a version and re-use any of the version numbers I created, and that they suggest releasing the ownership changes and updates under 2.0.0.

Thanks for being great and creating the package @martinthogersen!
